"use client";
const SASSY_MESSAGES = [
  "Ouch, was that really your best move? Let's pretend that didn't happen.",
  "I've seen better choices at a salad bar. Try again!",
  "Whoops! Did your cat walk on the keyboard on that turn?",
  "Even my grandma knows better... and she doesn't even play games!",
  "Well, that move was a swing and a miss! Strike one!",
  "If that was an attempt to impress, I'm underwhelmed.",
  "Next time, maybe consult a magic 8-ball first?",
  "Yikes, that choice was rougher than a sandpaper sandwich.",
  "That move was like a soggy firework. A total damp squib!",
  "I'm not saying that was a bad move, but I'm not not saying it either.",
  "Was that a strategic choice, or are you just making it up as you go?",
  "You really went out on a limb there... and sawed it off.",
  "Eek! Are you sure you didn’t mean to do literally anything else?",
  "If bad choices were an art, you'd be the Picasso of the game!",
  "Oh, honey, that was a no from me. And from the game.",
  "My turn to roll my eyes. That was... something.",
  "Did you mean to press that, or was it a slip of the finger?",
  "Hope you have better luck next time... you'll need it!",
  "That move was like a plot twist in a bad movie. Unnecessary.",
  "If this were chess, you'd be three moves from checkmate. Think harder!",
  "Well, that was an interesting choice. If by interesting, you mean baffling.",
  "On a scale of 1 to 10, that move was a solid ‘oops!’",
  "Even autocorrect couldn’t fix that move.",
  "It's a bold strategy, Cotton. Let's see if it pays off for them.",
  "That turn was a facepalm moment. And not just for you.",
  "I've seen toast make better decisions.",
  "Somewhere out there, a bridge is waiting for you to make better decisions under it.",
  "Your game strategy is like a mystery book with half the pages missing.",
  "You’re really paving the way... for everyone else to win!",
  "That move was so bad, even the dice are cringing.",
  "Oh, was that your best shot?",
  "Is that all you've got?",
  "Wow, you're really setting the bar low, aren't you?",
  "Did you mean to do that or was it an accident?",
  "Are you even trying?",
  "Maybe this game just isn't for you?",
  "Wow, I've seen toddlers play better!",
  "Did your cat walk across the keyboard or was that you?",
  "Oops! Was that as embarrassing for you as it was for me?",
  "Keep going, I need a good laugh!",
  "Wow, you're really consistent... consistently bad!",
  "Are you playing like this on purpose?",
  "Did you learn to play from a cereal box?",
  "Is this your strategy? Because it's... interesting.",
  "Are you sure you're not playing for the other team?",
  "Wow, you're really exploring the boundaries of failure, aren't you?",
  "Are you trying to set a new low score record?",
  "Did you think this was a game of 'who can do the worst'?",
  "Are you playing with your eyes closed?",
  "Are you sure you're not playing this game upside down?",
];

const SASSY_MOTIVATION = [
  "Every champion was once a contender that refused to give up. But let’s face it, not everyone’s cut out for the championship. Maybe your calling is being a glorious spectator? Keep trying though, miracles happen every day!",
  "Remember, every failure is a stepping stone to success. But honestly, you might be building a pyramid with those stones of yours. Keep stacking them though; it’s entertaining to watch, and who knows? You might actually get it right someday!",
  "They say you miss 100% of the shots you don’t take. And, at your current rate, about 99% of the ones you do. But who’s counting? Keep firing away! Statistically, you have to land something eventually, right?",
  "As the old saying goes, 'What doesn’t kill you makes you stronger.' Although, in your case, it just leaves you funnier and with more stories about what not to do. Keep living, keep learning, and most importantly, keep amusing us with your efforts!",
  "Greatness is a lot of small things done well, day after day. For you, it’s more like a bunch of random things done in a wonderfully questionable manner. But hey, at least you’re consistent in your inconsistency. Keep dazzling us with those unique strategies!",
  "It’s not about how hard you can hit; it’s about how hard you can get hit and keep moving forward. You’ve been taking those hits like a champ. Now, if only we could work on your dodging skills. You're turning resilience into an art form—one bruise at a time!",
  "Success is not final, failure is not fatal: It is the courage to continue that counts. You, my friend, have courage in spades. You’re like a heroic knight charging at windmills. Maybe misguided, but definitely brave. Keep charging, and maybe avoid windmills?",
];
const CONGRATULATION_MESSAGES = [
  "Brilliant performance! Your strategy and focus really paid off. Congratulations on a well-deserved victory!",
  "Well played! You really showed great skill and determination out there. You’re a true champion!",
  "Incredible game! Your ability to think ahead and anticipate moves is truly impressive. You've earned every bit of this win!",
  "What a masterful victory! You played like a pro and your hard work really shined through today. Great job!",
  "You’re a force to be reckoned with! Your tactical prowess and calm under pressure were the keys to your success. Well done!",
  "That was a stellar performance! You managed every challenge with grace and strategy. Congratulations on your win!",
  "Wow, what a game! Your creativity and persistence were amazing to watch. You truly deserve this victory!",
  "You played brilliantly and outsmarted the competition! It’s clear you put a lot of thought and effort into your game. Hats off to you!",
  "You’re a winner in every sense of the word! Your dedication and passion for the game really showed today. Fantastic win!",
  "Amazing job! You’ve really set a high bar with your gameplay. It's inspiring to see such talent in action.",
];
export const CONSTANTS = {
  SASSY_MESSAGES,
  SASSY_MOTIVATION,
  CONGRATULATION_MESSAGES,
};
